version: '2'

services:
  app:
    build: .
    command: npm run start
    entrypoint: ./entrypoint.sh
    environment:
      NODE_ENV: development
    volumes:
      - ./:/app
    ports:
      - "1337:1337"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
